"""Illustrative sample datasets used by the mock providers.

EVERYTHING IN THIS MODULE IS SYNTHETIC. The numbers are shaped like real
semiconductor financials so the pipeline exercises realistic code paths, but
they are not real reported figures and must never be presented as such. Each
source is tagged ``is_mock=True``, which propagates through normalisation into
the Evidence Store and is surfaced as a banner on the generated PDF.

Values are deliberately messy - strings with currency symbols and thousands
separators, percentages as text, several date formats and several metric naming
conventions - so the normalisation layer is genuinely exercised.

Fiscal convention used here: fiscal year N runs 1 Feb of year N to 31 Jan of
year N+1, so FY2026 Q2 ends 31 July 2026.
"""

from __future__ import annotations

from typing import Any

MOCK_NOTICE = (
    "Illustrative sample data generated by the prototype's mock providers. "
    "Not real reported figures."
)

# ---------------------------------------------------------------------------
# Market data
# ---------------------------------------------------------------------------

MARKET_SNAPSHOT: dict[str, dict[str, Any]] = {
    "NVDA": {
        "as_of": "2026-09-01",
        "quote": {
            "regularMarketPrice": 187.42,
            "previousClose": "184.10",
            "marketCap": "$4,560,000,000,000",
            "enterprise_value": 4_507_500_000_000,
            "regularMarketVolume": "214,300,000",
            "average_volume_30d": 198_700_000,
            "sharesOutstanding": "24,330,000,000",
            "fifty_two_week_high": 201.55,
            "fifty_two_week_low": "96.30",
        },
        "multiples": {
            "forwardPE": 31.4,
            "trailingPE": "42.8",
            "ev_sales": 18.6,
        },
        "consensus": {
            "analyst_rating": "Buy",
            "mean_price_target": "$215.00",
            "revisions_up": 24,
            "revisions_down": 5,
        },
        "estimates": [
            {"metric": "revenue_estimate", "value": "$64.90B", "period": "FY2026 Q3",
             "period_end": "2026-10-31"},
            {"metric": "eps_estimate", "value": 1.52, "period": "FY2026 Q3",
             "period_end": "2026-10-31"},
        ],
        # Weekly closes over the trailing year; the most recent point doubles
        # as the current price. Interpolated between monthly anchors with a
        # small deterministic ripple so the chart isn't a dead-straight line
        # between a handful of points.
        "price_history": [
            ("2025-09-01", 127.39), ("2025-09-09", 131.25), ("2025-09-16", 134.11), ("2025-09-23", 136.97),
            ("2025-10-01", 140.66), ("2025-10-08", 142.36), ("2025-10-14", 143.24), ("2025-10-21", 144.95),
            ("2025-10-27", 145.74), ("2025-11-03", 147.6), ("2025-11-10", 148.78), ("2025-11-17", 149.97),
            ("2025-11-24", 151.16), ("2025-12-01", 152.36), ("2025-12-09", 154.17), ("2025-12-16", 155.26),
            ("2025-12-23", 156.35), ("2025-12-31", 158.21), ("2026-01-07", 159.83), ("2026-01-13", 160.78),
            ("2026-01-20", 162.41), ("2026-01-26", 163.11), ("2026-02-02", 164.82), ("2026-02-09", 166.28),
            ("2026-02-16", 167.75), ("2026-02-23", 169.21), ("2026-03-02", 170.55), ("2026-03-10", 169.07),
            ("2026-03-17", 166.52), ("2026-03-24", 163.98), ("2026-04-01", 162.25), ("2026-04-09", 165.33),
            ("2026-04-16", 168.75), ("2026-04-23", 172.18), ("2026-05-01", 174.49), ("2026-05-09", 175.01),
            ("2026-05-17", 176.13), ("2026-05-24", 177.31), ("2026-06-01", 179.0), ("2026-06-09", 177.47),
            ("2026-06-16", 174.9), ("2026-06-23", 172.33), ("2026-07-01", 170.0), ("2026-07-08", 171.48),
            ("2026-07-14", 172.65), ("2026-07-21", 174.15), ("2026-07-27", 174.79), ("2026-08-03", 176.28),
            ("2026-08-10", 179.05), ("2026-08-17", 181.83), ("2026-08-25", 185.62), ("2026-09-01", 187.42),
        ],
        # Historical forward P/E observations, used for valuation-vs-history.
        "forward_pe_history": [
            ("2025-09-01", 28.9), ("2025-12-01", 30.2), ("2026-03-02", 33.6),
            ("2026-06-01", 29.8),
        ],
    }
}

PEER_MARKET_SNAPSHOT: dict[str, dict[str, Any]] = {
    "AMD": {"forwardPE": 27.8, "ev_sales": 7.9, "marketCap": 315_000_000_000,
            "revenue_growth_yoy_pct": 22.4},
    "INTC": {"forwardPE": 19.6, "ev_sales": 2.4, "marketCap": 118_000_000_000,
             "revenue_growth_yoy_pct": -3.1},
    "AVGO": {"forwardPE": 34.2, "ev_sales": 16.1, "marketCap": 1_240_000_000_000,
             "revenue_growth_yoy_pct": 28.7},
}


# ---------------------------------------------------------------------------
# Fundamentals
# ---------------------------------------------------------------------------

#: Reported income-statement / cash-flow / balance-sheet lines by fiscal period.
#: Values intentionally mix numeric and string representations.
FUNDAMENTALS: dict[str, dict[str, dict[str, Any]]] = {
    "NVDA": {
        "FY2026 Q2": {
            "period_end": "2026-07-31",
            "lines": {
                "totalRevenue": "$62,300,000,000",
                "cost_of_revenue": 15_700_000_000,
                "gross_profit": 46_600_000_000,
                "Gross Margin": "74.8%",
                "operating_income": 41_900_000_000,
                "Operating Margin": "67.3%",
                "netIncome": 35_200_000_000,
                "eps": 1.43,
                "cash_flow_from_operations": 38_400_000_000,
                "capital_expenditure": 2_100_000_000,
                "free_cashflow": 36_300_000_000,
                "cash_and_cash_equivalents": 61_000_000_000,
                "total_debt": 8_500_000_000,
                "research_and_development": 4_900_000_000,
            },
        },
        "FY2026 Q1": {
            "period_end": "2026-04-30",
            "lines": {
                "totalRevenue": 55_800_000_000,
                "cost_of_revenue": 14_400_000_000,
                "gross_profit": 41_400_000_000,
                "Gross Margin": "74.2%",
                "operating_income": 36_700_000_000,
                "Operating Margin": "65.8%",
                "netIncome": 30_900_000_000,
                "eps": 1.26,
                "cash_flow_from_operations": 33_100_000_000,
                "capital_expenditure": 1_900_000_000,
                "free_cashflow": 31_200_000_000,
                "cash_and_cash_equivalents": 54_200_000_000,
                "total_debt": 8_500_000_000,
                "research_and_development": 4_500_000_000,
            },
        },
        "FY2025 Q2": {
            "period_end": "2025-07-31",
            "lines": {
                "totalRevenue": 40_100_000_000,
                "cost_of_revenue": 9_744_000_000,
                "gross_profit": 30_356_000_000,
                "Gross Margin": "75.7%",
                "operating_income": 26_300_000_000,
                "Operating Margin": "65.6%",
                "netIncome": 22_100_000_000,
                "eps": 0.89,
                "cash_flow_from_operations": 24_600_000_000,
                "capital_expenditure": 1_300_000_000,
                "free_cashflow": 23_300_000_000,
                "cash_and_cash_equivalents": 42_800_000_000,
                "total_debt": 9_700_000_000,
                "research_and_development": 3_400_000_000,
            },
        },
    }
}

#: Reported revenue by business segment.
SEGMENTS: dict[str, dict[str, dict[str, float]]] = {
    "NVDA": {
        "FY2026 Q2": {
            "Data Center": 54_200_000_000,
            "Gaming": 4_600_000_000,
            "Professional Visualization": 650_000_000,
            "Automotive": 750_000_000,
            "OEM and Other": 2_100_000_000,
        },
        "FY2025 Q2": {
            "Data Center": 33_800_000_000,
            "Gaming": 3_900_000_000,
            "Professional Visualization": 540_000_000,
            "Automotive": 570_000_000,
            "OEM and Other": 1_290_000_000,
        },
        "FY2026 Q1": {
            "Data Center": 48_100_000_000,
            "Gaming": 4_350_000_000,
            "Professional Visualization": 610_000_000,
            "Automotive": 690_000_000,
            "OEM and Other": 2_050_000_000,
        },
    }
}

#: Company-specific operating KPIs.
KPIS: dict[str, list[dict[str, Any]]] = {
    "NVDA": [
        {"name": "Networking revenue", "value": 8_900_000_000, "unit": "USD",
         "period": "FY2026 Q2", "period_end": "2026-07-31"},
        {"name": "Networking revenue", "value": 4_100_000_000, "unit": "USD",
         "period": "FY2025 Q2", "period_end": "2025-07-31"},
        {"name": "Purchase commitments and supply obligations", "value": 42_000_000_000,
         "unit": "USD", "period": "FY2026 Q2", "period_end": "2026-07-31"},
        {"name": "Inventory", "value": 19_400_000_000, "unit": "USD",
         "period": "FY2026 Q2", "period_end": "2026-07-31"},
        {"name": "Inventory", "value": 11_200_000_000, "unit": "USD",
         "period": "FY2025 Q2", "period_end": "2025-07-31"},
    ]
}

#: Sell-side consensus for the reported period (drives surprise analytics).
CONSENSUS: dict[str, list[dict[str, Any]]] = {
    "NVDA": [
        {"metric": "revenue_consensus", "value": 59_800_000_000, "period": "FY2026 Q2",
         "period_end": "2026-07-31"},
        {"metric": "eps_consensus", "value": 1.36, "period": "FY2026 Q2",
         "period_end": "2026-07-31"},
        {"metric": "revenue_consensus", "value": 64_900_000_000, "period": "FY2026 Q3",
         "period_end": "2026-10-31"},
        {"metric": "eps_consensus", "value": 1.52, "period": "FY2026 Q3",
         "period_end": "2026-10-31"},
    ]
}

#: Management guidance issued alongside the latest results.
GUIDANCE: dict[str, list[dict[str, Any]]] = {
    "NVDA": [
        {"metric": "revenue_guidance", "value": "$66.50B", "period": "FY2026 Q3",
         "period_end": "2026-10-31",
         "note": "Midpoint of the guided range, plus or minus 2%."},
        {"metric": "gross_margin_guidance", "value": "75.5%", "period": "FY2026 Q3",
         "period_end": "2026-10-31", "note": "Non-GAAP gross margin midpoint."},
    ]
}


# ---------------------------------------------------------------------------
# Documents
# ---------------------------------------------------------------------------

#: Documents and the passages extracted from them.
#: ``source_type`` values match eq_report.domain.enums.SourceType.
DOCUMENTS: dict[str, list[dict[str, Any]]] = {
    "NVDA": [
        {
            "title": "NVIDIA Announces Financial Results for Second Quarter Fiscal 2026",
            "source_type": "earnings_release",
            "publisher": "NVIDIA Corporation Investor Relations",
            "published": "Aug 19, 2026",
            "url": "https://example.invalid/nvda/fy2026-q2-earnings-release",
            "passages": [
                {"section": "Highlights",
                 "text": "Revenue for the second quarter of fiscal 2026 was $62.30 billion, "
                         "up 55% from a year ago and up 12% from the previous quarter."},
                {"section": "Highlights",
                 "text": "Data Center revenue was $54.20 billion, up 60% from a year ago, "
                         "driven by continued ramp of the company's latest accelerated "
                         "computing platform."},
                {"section": "Outlook",
                 "text": "Revenue for the third quarter of fiscal 2026 is expected to be "
                         "$66.50 billion, plus or minus 2%.",
                 "speaker": "Company outlook"},
                {"section": "Outlook",
                 "text": "Non-GAAP gross margin is expected to be 75.5% for the third "
                         "quarter, plus or minus 50 basis points.",
                 "speaker": "Company outlook"},
            ],
        },
        {
            "title": "Quarterly Report on Form 10-Q for the quarter ended July 31, 2026",
            "source_type": "company_filing",
            "publisher": "U.S. Securities and Exchange Commission (EDGAR)",
            "published": "2026-08-22",
            "url": "https://example.invalid/edgar/nvda/10-q-fy2026-q2",
            "passages": [
                {"section": "Item 2 - MD&A",
                 "text": "Purchase commitments and obligations for inventory and capacity "
                         "totalled $42.00 billion as of July 31, 2026, reflecting the "
                         "company's efforts to secure supply for anticipated demand."},
                {"section": "Item 1A - Risk Factors",
                 "text": "A limited number of customers accounted for a significant portion "
                         "of revenue, and the loss of, or a reduction in purchases by, any "
                         "of these customers could materially harm results of operations."},
                {"section": "Item 1A - Risk Factors",
                 "text": "Export licensing requirements applicable to certain accelerated "
                         "computing products may continue to restrict sales into affected "
                         "regions and could adversely affect future revenue."},
                {"section": "Notes to Financial Statements",
                 "text": "Inventories were $19.40 billion as of July 31, 2026, compared with "
                         "$11.20 billion a year earlier."},
            ],
        },
        {
            "title": "NVIDIA Second Quarter Fiscal 2026 Earnings Call Transcript",
            "source_type": "earnings_call",
            "publisher": "Company earnings call transcript",
            "published": "19/08/2026",
            "url": "https://example.invalid/nvda/fy2026-q2-transcript",
            "passages": [
                {"section": "Prepared remarks", "speaker": "Chief Executive Officer",
                 "text": "Demand for our accelerated computing platform continues to exceed "
                         "supply, and we expect that to remain the case through the end of "
                         "the fiscal year."},
                {"section": "Prepared remarks", "speaker": "Chief Financial Officer",
                 "text": "Gross margin declined sequentially and year over year as the new "
                         "platform ramps; we expect margins to recover towards the high 70s "
                         "as the ramp matures and yields improve."},
                {"section": "Q&A", "speaker": "Chief Executive Officer",
                 "text": "Networking is becoming an increasingly important part of the data "
                         "centre opportunity, and attach rates continue to rise."},
                {"section": "Q&A", "speaker": "Chief Financial Officer",
                 "text": "We are not assuming any revenue from restricted regions in our "
                         "third quarter outlook."},
            ],
        },
        {
            "title": "NVIDIA Q2 FY2026 Investor Presentation",
            "source_type": "investor_presentation",
            "publisher": "NVIDIA Corporation Investor Relations",
            "published": "2026-08-19",
            "url": "https://example.invalid/nvda/fy2026-q2-deck",
            "passages": [
                {"section": "Slide 6",
                 "text": "Data Center now represents 87% of total revenue, up from 84% a "
                         "year ago."},
                {"section": "Slide 11",
                 "text": "Networking revenue more than doubled year over year to $8.90 "
                         "billion."},
            ],
        },
        {
            "title": "NVIDIA Announces Next-Generation Accelerated Computing Platform "
                     "Availability",
            "source_type": "company_announcement",
            "publisher": "NVIDIA Corporation",
            "published": "2026-07-14",
            "url": "https://example.invalid/nvda/platform-availability",
            "passages": [
                {"section": "Press release",
                 "text": "The company announced general availability of its next-generation "
                         "accelerated computing platform, with initial systems shipping to "
                         "cloud service providers during the third fiscal quarter."},
            ],
        },
        {
            "title": "NVIDIA and a major cloud provider expand multi-year capacity agreement",
            "source_type": "company_announcement",
            "publisher": "NVIDIA Corporation",
            "published": "2026-08-05",
            "url": "https://example.invalid/nvda/cloud-capacity-agreement",
            "passages": [
                {"section": "Press release",
                 "text": "The companies announced an expanded multi-year agreement covering "
                         "additional accelerated computing capacity to be deployed through "
                         "calendar 2028."},
            ],
        },
        {
            "title": "Regulators signal further review of accelerated computing exports",
            "source_type": "news",
            "publisher": "Illustrative Newswire",
            "published": "2026-08-28",
            "url": "https://example.invalid/news/export-review",
            "passages": [
                {"section": "Article",
                 "text": "Officials indicated that licensing requirements for advanced "
                         "accelerated computing hardware would remain under review, keeping "
                         "uncertainty over shipments into affected regions."},
            ],
        },
        {
            "title": "Hyperscaler capital expenditure guidance raised for calendar 2027",
            "source_type": "news",
            "publisher": "Illustrative Newswire",
            "published": "2026-08-12",
            "url": "https://example.invalid/news/hyperscaler-capex",
            "passages": [
                {"section": "Article",
                 "text": "Several large cloud providers raised capital expenditure plans for "
                         "calendar 2027, with the majority of incremental spend directed at "
                         "accelerated computing infrastructure."},
            ],
        },
        {
            "title": "Advanced Micro Devices Quarterly Report on Form 10-Q",
            "source_type": "competitor_filing",
            "publisher": "U.S. Securities and Exchange Commission (EDGAR)",
            "published": "2026-08-06",
            "url": "https://example.invalid/edgar/amd/10-q",
            "passages": [
                {"section": "Item 2 - MD&A",
                 "text": "Data centre segment revenue grew 22% year over year, with the "
                         "company citing improving customer adoption of its accelerator "
                         "portfolio."},
            ],
        },
        {
            "title": "Accelerated computing market outlook, mid-2026 update",
            "source_type": "industry_research",
            "publisher": "Illustrative Industry Research",
            "published": "2026-07-30",
            "url": "https://example.invalid/research/accelerator-market-2026",
            "passages": [
                {"section": "Market sizing",
                 "text": "The accelerated computing hardware market is estimated to have "
                         "grown 48% year over year in the first half of calendar 2026, with "
                         "the incumbent supplier retaining the majority of unit share."},
                {"section": "Competitive dynamics",
                 "text": "Custom silicon programmes at large cloud providers are expected to "
                         "take a growing share of internal workloads, though supply "
                         "constraints continue to favour merchant suppliers in the near term."},
            ],
        },
    ]
}


# ---------------------------------------------------------------------------
# Apple fixture
# ---------------------------------------------------------------------------
# Like the NVDA fixture above, this is intentionally synthetic. It exists to
# exercise the full research pipeline when live sources are unavailable; it is
# not a substitute for the SEC/Yahoo adapter or for published research.
MARKET_SNAPSHOT["AAPL"] = {
    "as_of": "2026-09-09",
    "quote": {"regularMarketPrice": 223.67, "previousClose": 221.40,
              "marketCap": "$3,320,000,000,000", "enterprise_value": 3_270_000_000_000,
              "regularMarketVolume": "51,800,000", "average_volume_30d": 48_600_000,
              "sharesOutstanding": "14,850,000,000", "fifty_two_week_high": 241.20,
              "fifty_two_week_low": 171.80},
    "multiples": {"forwardPE": 27.6, "trailingPE": "32.4", "ev_sales": 8.2},
    "consensus": {"analyst_rating": "Buy", "mean_price_target": "$242.00",
                  "revisions_up": 18, "revisions_down": 7},
    "estimates": [{"metric": "revenue_estimate", "value": "$108.40B", "period": "FY2026 Q4", "period_end": "2026-09-26"},
                  {"metric": "eps_estimate", "value": 1.86, "period": "FY2026 Q4", "period_end": "2026-09-26"}],
    "price_history": [("2025-09-01", 189.2), ("2025-10-01", 195.4), ("2025-11-03", 201.1),
                      ("2025-12-01", 207.3), ("2025-12-31", 211.8), ("2026-01-30", 205.6),
                      ("2026-02-27", 198.7), ("2026-03-31", 204.1), ("2026-04-30", 211.6),
                      ("2026-05-29", 216.4), ("2026-06-30", 219.8), ("2026-07-31", 217.3),
                      ("2026-08-28", 221.2), ("2026-09-09", 223.67)],
    "forward_pe_history": [("2025-09-01", 25.2), ("2025-12-01", 26.1), ("2026-03-31", 24.8), ("2026-06-30", 27.1)],
}
PEER_MARKET_SNAPSHOT.update({
    "MSFT": {"forwardPE": 30.1, "ev_sales": 12.4, "marketCap": 3_650_000_000_000, "revenue_growth_yoy_pct": 14.6},
    "GOOGL": {"forwardPE": 23.8, "ev_sales": 7.1, "marketCap": 2_500_000_000_000, "revenue_growth_yoy_pct": 13.2},
    "DELL": {"forwardPE": 18.5, "ev_sales": 1.3, "marketCap": 103_000_000_000, "revenue_growth_yoy_pct": 9.1},
})
FUNDAMENTALS["AAPL"] = {
    "FY2026 Q3": {"period_end": "2026-06-27", "lines": {
        "totalRevenue": "$101,200,000,000", "cost_of_revenue": 52_100_000_000, "gross_profit": 49_100_000_000,
        "Gross Margin": "48.5%", "operating_income": 30_600_000_000, "Operating Margin": "30.2%",
        "netIncome": 24_900_000_000, "eps": 1.68, "cash_flow_from_operations": 31_700_000_000,
        "capital_expenditure": 2_700_000_000, "free_cashflow": 29_000_000_000, "cash_and_cash_equivalents": 38_600_000_000,
        "total_debt": 91_400_000_000, "research_and_development": 9_100_000_000}},
    "FY2026 Q2": {"period_end": "2026-03-28", "lines": {
        "totalRevenue": 96_800_000_000, "cost_of_revenue": 50_500_000_000, "gross_profit": 46_300_000_000,
        "Gross Margin": "47.8%", "operating_income": 28_700_000_000, "Operating Margin": "29.6%",
        "netIncome": 23_100_000_000, "eps": 1.55, "cash_flow_from_operations": 28_900_000_000,
        "capital_expenditure": 2_600_000_000, "free_cashflow": 26_300_000_000, "cash_and_cash_equivalents": 34_900_000_000,
        "total_debt": 94_300_000_000, "research_and_development": 8_700_000_000}},
    "FY2025 Q3": {"period_end": "2025-06-28", "lines": {
        "totalRevenue": 92_600_000_000, "cost_of_revenue": 49_300_000_000, "gross_profit": 43_300_000_000,
        "Gross Margin": "46.8%", "operating_income": 26_100_000_000, "Operating Margin": "28.2%",
        "netIncome": 21_300_000_000, "eps": 1.42, "cash_flow_from_operations": 26_500_000_000,
        "capital_expenditure": 2_300_000_000, "free_cashflow": 24_200_000_000, "cash_and_cash_equivalents": 31_800_000_000,
        "total_debt": 98_100_000_000, "research_and_development": 7_900_000_000}},
}
SEGMENTS["AAPL"] = {
    "FY2026 Q3": {"iPhone": 49_400_000_000, "Mac": 8_200_000_000, "iPad": 6_700_000_000,
                  "Wearables, Home and Accessories": 9_100_000_000, "Services": 27_800_000_000},
    "FY2025 Q3": {"iPhone": 45_500_000_000, "Mac": 7_300_000_000, "iPad": 6_000_000_000,
                  "Wearables, Home and Accessories": 8_700_000_000, "Services": 25_100_000_000},
    "FY2026 Q2": {"iPhone": 47_100_000_000, "Mac": 8_000_000_000, "iPad": 6_400_000_000,
                  "Wearables, Home and Accessories": 8_900_000_000, "Services": 26_400_000_000},
}
KPIS["AAPL"] = [
    {"name": "Services revenue", "value": 27_800_000_000, "unit": "USD", "period": "FY2026 Q3", "period_end": "2026-06-27"},
    {"name": "Services revenue", "value": 25_100_000_000, "unit": "USD", "period": "FY2025 Q3", "period_end": "2025-06-28"},
    {"name": "Installed base", "value": 2_450_000_000, "unit": "count", "period": "FY2026 Q3", "period_end": "2026-06-27"},
]
CONSENSUS["AAPL"] = [
    {"metric": "revenue_consensus", "value": 98_700_000_000, "period": "FY2026 Q3", "period_end": "2026-06-27"},
    {"metric": "eps_consensus", "value": 1.61, "period": "FY2026 Q3", "period_end": "2026-06-27"},
    {"metric": "revenue_consensus", "value": 108_400_000_000, "period": "FY2026 Q4", "period_end": "2026-09-26"},
    {"metric": "eps_consensus", "value": 1.86, "period": "FY2026 Q4", "period_end": "2026-09-26"},
]
GUIDANCE["AAPL"] = [
    {"metric": "revenue_guidance", "value": "$109.50B", "period": "FY2026 Q4", "period_end": "2026-09-26", "note": "Illustrative midpoint."},
    {"metric": "gross_margin_guidance", "value": "48.8%", "period": "FY2026 Q4", "period_end": "2026-09-26", "note": "Illustrative midpoint."},
]
DOCUMENTS["AAPL"] = [
    {"title": "Apple Illustrative FY2026 Q3 Results", "source_type": "earnings_release", "publisher": "Apple Investor Relations (illustrative)", "published": "2026-07-30", "url": "https://example.invalid/aapl/q3-results", "passages": [
        {"section": "Highlights", "text": "Illustrative FY2026 Q3 revenue was $101.2 billion, up 9% year over year, led by iPhone and Services growth."},
        {"section": "Outlook", "speaker": "Company outlook", "text": "Illustrative FY2026 Q4 revenue is expected to be $109.5 billion, with gross margin of approximately 48.8%."}]},
    {"title": "Apple Illustrative FY2026 Q3 Form 10-Q", "source_type": "company_filing", "publisher": "SEC EDGAR (illustrative)", "published": "2026-08-01", "url": "https://example.invalid/aapl/q3-10q", "passages": [
        {"section": "MD&A", "text": "Services remained the fastest-growing revenue category in this illustrative dataset, supporting mix and gross-margin resilience."},
        {"section": "Risk Factors", "text": "The illustrative scenario assumes demand, supply-chain, foreign-exchange, regulatory and competitive risks remain material to hardware results."}]},
    {"title": "Apple Illustrative Earnings Call", "source_type": "earnings_call", "publisher": "Company earnings call (illustrative)", "published": "2026-07-30", "url": "https://example.invalid/aapl/q3-call", "passages": [
        {"section": "Prepared remarks", "speaker": "Chief Executive Officer", "text": "The illustrative scenario assumes an expanding installed base and continued Services engagement."},
        {"section": "Prepared remarks", "speaker": "Chief Financial Officer", "text": "The illustrative outlook assumes a broadly stable gross-margin profile despite product and geographic mix movements."}]},
    {"title": "Apple Illustrative Product Update", "source_type": "company_announcement", "publisher": "Apple (illustrative)", "published": "2026-09-01", "url": "https://example.invalid/aapl/product-update", "passages": [
        {"section": "Announcement", "text": "The illustrative scenario includes a new product-cycle launch intended to support fiscal fourth-quarter demand."}]},
    {"title": "Consumer Electronics Market Update", "source_type": "industry_research", "publisher": "Illustrative Industry Research", "published": "2026-08-20", "url": "https://example.invalid/aapl/industry", "passages": [
        {"section": "Market", "text": "The illustrative market view assumes premium smartphone demand remains uneven across regions, while recurring services continue to grow faster than hardware."}]},
]


def has_sample_data(ticker: str | None) -> bool:
    """Whether the sample dataset covers this ticker."""
    return bool(ticker) and ticker in FUNDAMENTALS
